baseurl = "https://gostevedore.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "gostevedore"
theme = "syna"
enableGitInfo = true
version = "0.17.4"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
ignorefiles = [ "content/dev/.*" ]

[params]
  name = "gostevedore"
  title ="The docker images factory"
  description = "Stevedore is a useful tool when you need to manage a bunch of Docker images in a standardized way, such on a microservices architecture. It lets you to define how to build your Docker images and their parent-child relationship. It builds automatically the children images when its parent are done. And many other features which improve the Docker image's building process. Is not a Dockerfile's alternative, but how to use them to build your images"
  author = "Aleix Penella"
  image = "https://gostevedore.github.io/images/logo.png"

  [params.custom]
    favicon_ico_sizes = "16x16 32x32 48x48"
    favicon = "images/favicon.ico"
    favicon_png = "images/favicon.png"
    favicon_svg = "images/favicon.svg"

  [params.colors]
    primary = "#AA0088"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#363636"
