# baseURL: "https://gostevedore.github.io/"
# languageCode: "en-us"
# title: "stevedore"
# theme: "syna"
# params:
#   author: Aleix Penella
#   description: Stevedore manages and governs the Docker image's building process
#   name: gostevedore

baseurl = "https://gostevedore.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "stevedore"
theme = "syna"
enableGitInfo = true
version = "0.17.4"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
ignorefiles = [ "content/dev/.*" ]

[params]
  name = "stevedore"
  description = "A way of manage and govern the Docker image's building process"
  author = "Aleix Penella"

  [params.custom]
    favicon_ico_sizes = "16x16 32x32 48x48"
    favicon = "images/favicon.ico"
    favicon_png = "images/favicon.png"
    favicon_svg = "images/favicon.svg"

  [params.colors]
    primary = "#AA0088"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#363636"
